# docker-compose.yml

version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres_container
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: contraseña
      POSTGRES_DB: MentalNow
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  api:
    build: ./api
    container_name: api_container
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: MentalNow
      DB_USER: usuario
      DB_PASSWORD: contraseña
    depends_on:
      - db
    ports:
      - "5000:5000"

volumes:
  db_data:
